New rails project/Blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  	resources :posts
  end
  root 'welcome#index'
end

New rails project/Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

New rails project/Blog/app/models/post.rb
class Post < ApplicationRecord
end

New rails project/Blog/app/models/user.rb
class User < ApplicationRecord
end

New rails project/Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

New rails project/Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
	end

	def index
		@posts = Post.all
	end
	def show 
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to @post
	end

	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

New rails project/Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])	
	end
	def create
		@user = User.new(user_params)
		@user.save
		redirect_to @user
	end
	private
		def user_params
			params.require(:user).permit(:username, :email)
		end
end

New rails project/Blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

New rails project/Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

New rails project/Blog/app/helpers/posts_helper.rb
module PostsHelper
end

New rails project/Blog/app/helpers/users_helper.rb
module UsersHelper
end

New rails project/Blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

New rails project/Blog/app/views/posts/_post.html.erb
<tr>
  <td><%= post.id %></td>
  <td><%= post.title %></td>
  <td><%= post.text %></td>
  <td><%= link_to 'Show', "#" %></td>
</tr>

New rails project/Blog/app/views/posts/index.html.erb
<h1>Listing posts</h1>
 <%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
    </tr>
  <% end %>
</table>

New rails project/Blog/app/views/posts/new.html.erb
<%= form_with scope: :post, url: posts_path ,local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

New rails project/Blog/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

New rails project/Blog/app/views/welcome/index.html.erb
<h1>Home Blog</h1>

<%= link_to 'User', controller: 'users' %>