New rails project/demo_login1/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # devise_for :admins
  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"
  root "articles#index"
  post "forgot_pass" => "users#find_pass"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :articles do
  	resources :comments
  end
  namespace :admin do
    resources :users  
    resources :articles do
      resources :comments
    end
    root 'admin#show'
  end
end

New rails project/demo_login1/app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <li class="navbar-brand"><%= link_to "Blog", articles_path %></li>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Article
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Add Article", new_article_path(@current_user) %></li>      
          <% if current_user.authorities %>
            <li><%= link_to "My Facebook", 'https://www.facebook.com/gruhhhhh' %></li>
          <% end %>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">User
        <span class="caret"></span></a>
        <ul class="dropdown-menu">

          <li><%= link_to "My Blog", user_path(current_user) %></li>

        </ul>
      </li>

    </ul>

    <ul class="nav navbar-nav navbar-right">
      <div class="navbar-form navbar-left">
          <form id="search_box">
            <input type="text" name="search" placeholder="Search..">
          </form>
      </div>
      <div class="navbar-header navbar-brand">

        <div class="dropdown">
          <a data-toggle="dropdown" href="#"><%= current_user.name %></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <% if current_user.authorities %>

                <li role="presentation"><a role="menuitem" tabindex="-1">
                <td><%= link_to "List Users", users_path %></td>
                </a></li>

            <% end %>
            <li role="presentation"><a role="menuitem" tabindex="-1">
                <td><%= link_to 'Edit', edit_user_path(current_user) %></td>
            </a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1">
                <td><%= link_to "Logout",  logout_path ,
                  method: :delete
                 %></td>
            </a></li>
          </ul>
        </div>


        <!-- <li class="navbar-brand"><%= link_to current_user.name, user_path(@current_user) %></li> -->
      </div>
     <!--  <li> <%= link_to "Logout", logout_path, method: :delete %></li> -->
    </ul>
  </div>
</nav> 