New rails project/demo_login1/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # devise_for :admins
  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"
  root "articles#index"
  post "forgot_pass" => "users#find_pass"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :articles do
  	resources :comments
  end
  namespace :admin do
    resources :users  
    resources :articles do
      resources :comments
    end
    root 'admin#show'
  end
end

New rails project/demo_login1/app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
	skip_before_action :require_login
	private
	
	def after_sign_out_path_for(resource)
		login_path
	end
end

New rails project/demo_login1/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:new,:create]
  def new
    if session[:user_id].present?
      redirect_to user_path(session[:user_id])
    end
    @user = User.new
  end
  def create
  	user = User.find_by name: params[:session][:name].downcase
  	if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to articles_path
  	else
  		flash[:danger] = "Invalid email/password combination"
  		redirect_to login_path
  	end
  end
  def destroy
  	log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end

end

New rails project/demo_login1/app/helpers/session_helper.rb
module SessionHelper
	def log_in user
		session[:user_id] = user.id
	end
	def log_out
    	session.delete :user_id
	end
	def current_user
		@current_user ||= User.find_by id: session[:user_id]
	end

	def logged_in?
		current_user.present?
	end
	def is_a_valid_email? email
  		email =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	end
end
 

New rails project/demo_login1/app/views/session/new.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center">Login</h1>
	</div>
	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<%= form_for :session, url: login_path do |f| %>
				<div class="form-group">
					<%= f.label :"user name" %>
					<%= f.text_field :name, placeholder: "Enter user name", class: "form-control" %>
				</div>
				<div class="form-group" id="show">
					<%= f.label :password %>
					<%= f.password_field :password, placeholder: "Enter your password",
						class: "form-control" %>
				</div>
				<div class="text-center">
					<%= f.submit "Sign in", class: "btn btn-info col-lg-12" %>
				</div>
				<div class="text-right">
					<%= link_to "Sign Up", new_user_path %>
				</div>
				<div class="text-right">
					<a href="#" data-toggle="modal" data-target="#myModal" >Forgot your password ? </a>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Forgot Password</h4>
        <% if params[:flag] %> 
        	<p class="text-danger"><%= params[:message] %></p>
        <% end %>
      </div>
      <div class="modal-body">
		<%= form_for @user, :url => {:controller => "users", :action => "find_pass"} ,html: {class: "form-horizontal" } do |f| %>
	      <div class="form-group">
	        <%= f.label :name, "User Name", class: "col-md-4 control-label" %>
	        <div class="col-md-6">
	          <%= f.text_field :name, class: "form-control", placeholder: "Enter your user name" %>
	        </div>
	      </div>
	      <div class="form-group">
	        <%= f.label :email, class: "col-md-4 control-label" %>
	        <div class="col-md-6">
	          <%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %>
	        </div>
	      </div>
	      <div class="form-group">
	        <%= f.label :password, "New password", class: "col-md-4 control-label" %>
	        <div class="col-md-6">
	          <%= f.password_field :password, class: "form-control", placeholder: "Enter your new password" %>
	        </div>
	      </div>
	      <div class="form-group">
	        <%= f.label :password_confirmation, "Confirm new password", class: "col-md-4 control-label" %>
	        <div class="col-md-6">
	          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your new password" %>
	        </div>
	      </div>
	      <div class="form-group">
	        <div class="col-lg-offset-4">
	          <%= f.submit "Confirm", class: "btn btn-primary" %>
	        </div>
	      </div>
	    <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
	<% if params[:flag] %> 
	    $(window).on('load',function(){

	        $('#myModal').modal('show');
	    });
	<% end %>
</script>